name: 'Delete old artifacts'
on:
  push:
    branches:
      - main
      - action-testing
      - delete-artifasts
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.PAT_ARTIFACTS }}
          expire-in: 0 # Setting this to 0 will delete all artifacts